name: publish

on:
    release:
        types: [released]

permissions:
    contents: read

jobs:
    publish:
        runs-on: ubuntu-latest
        if: ${{ vars.NPM_PUBLISH_ENABLED == 'true' }}
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
            - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
              with:
                  cache: false
              env:
                  GITHUB_TOKEN: ${{ github.token }}
            - run: just build
            - run: vp run prepack
            - uses: JS-DevTools/npm-publish@0fd2f4369c5d6bcfcde6091a7c527d810b9b5c3f # v4.1.5
              with:
                  token: ${{ secrets.NPM_TOKEN }}
            - run: vp run postpack
